repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: stable
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: double-quote-string-fixer
-   repo: https://gitlab.com/pycqa/flake8
    rev: stable
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: stable
    hooks:
    -   id: yapf
-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: 1.0.4
    hooks:
      - id: python-import-sorter
        args: ['--check-only']